-- ============================================================
--  Fiche de securite d'une seance (A322-72 du Code du sport) :
--  conditions du jour, securite surface, plan de secours, et le
--  detail par palanquee (palanquee / membre_palanquee).
--
--  fiche_securite est modifiable, historisee via Envers comme le
--  reste des entites de ce type (voir V6). Les palanquees et leurs
--  membres n'ont pas d'existence propre en dehors de la fiche : ce
--  sont des lignes remplacees en bloc a chaque enregistrement,
--  comme participation, pas des entites auditees individuellement.
-- ============================================================

CREATE TABLE fiche_securite (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    seance_id         BIGINT NOT NULL UNIQUE REFERENCES seance(id) ON DELETE CASCADE,
    dp_id             BIGINT NOT NULL REFERENCES utilisateur(id),
    meteo             VARCHAR(120),
    etat_mer          VARCHAR(120),
    visibilite        VARCHAR(120),
    courant           VARCHAR(120),
    maree             VARCHAR(120),
    temperature_eau   VARCHAR(120),
    securite_surface  TEXT,
    plan_secours      TEXT,
    observations      TEXT
);

-- Le profil de plongee (profondeur, duree, paliers, heures) est porte par la
-- palanquee : c'est le groupe qui plonge ensemble sur un meme profil, pas
-- chaque plongeur individuellement. Prevu et realise sont saisis a deux
-- moments distincts (etablissement de la fiche, puis retour de plongee).
CREATE TABLE palanquee (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fiche_securite_id    BIGINT NOT NULL REFERENCES fiche_securite(id) ON DELETE CASCADE,
    numero               INT    NOT NULL,
    profondeur_prevue    INT,
    duree_prevue         INT,
    profondeur_realisee  INT,
    duree_realisee       INT,
    paliers              VARCHAR(60),
    heure_immersion      TIME,
    heure_sortie         TIME
);
CREATE INDEX idx_palanquee_fiche ON palanquee(fiche_securite_id);

-- Seuls le gaz et le moyen de desaturation varient d'un plongeur a l'autre
-- au sein d'une meme palanquee. eleve_id/utilisateur_id sont facultatifs et
-- mutuellement exclusifs : ils pre-remplissent aptitude/qualification_preparee
-- depuis le dossier d'un membre du club, sans empecher de citer un invite qui
-- n'y figure pas (nom/prenom restent obligatoires et editables dans tous les cas).
CREATE TABLE membre_palanquee (
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    palanquee_id           BIGINT NOT NULL REFERENCES palanquee(id) ON DELETE CASCADE,
    eleve_id               BIGINT REFERENCES eleve(id),
    utilisateur_id         BIGINT REFERENCES utilisateur(id),
    nom                    VARCHAR(80)  NOT NULL,
    prenom                 VARCHAR(80)  NOT NULL,
    aptitude               VARCHAR(60),
    qualification_preparee VARCHAR(10),
    fonction               VARCHAR(20)  NOT NULL DEFAULT 'PLONGEUR',
    gaz                    VARCHAR(40),
    moyen_desaturation     VARCHAR(60),
    observations           TEXT,
    CONSTRAINT ck_fonction_palanquee CHECK (fonction IN ('PLONGEUR','GUIDE_PALANQUEE','ENCADRANT')),
    CONSTRAINT ck_membre_lien CHECK (eleve_id IS NULL OR utilisateur_id IS NULL)
);
CREATE INDEX idx_membre_palanquee_palanquee ON membre_palanquee(palanquee_id);

-- Audit Envers (voir V6__audit_envers.sql pour les conventions).
CREATE TABLE fiche_securite_aud (
    rev              INTEGER NOT NULL REFERENCES revision_audit(id),
    revtype          SMALLINT,
    id               BIGINT  NOT NULL,
    seance_id        BIGINT,
    dp_id            BIGINT,
    meteo            VARCHAR(120),
    etat_mer         VARCHAR(120),
    visibilite       VARCHAR(120),
    courant          VARCHAR(120),
    maree            VARCHAR(120),
    temperature_eau  VARCHAR(120),
    securite_surface TEXT,
    plan_secours     TEXT,
    observations     TEXT,
    PRIMARY KEY (rev, id)
);
