-- ============================================================
--  Groupe nomme et reutilisable de plongeurs (typiquement constitue
--  pour un sejour), glisse-depose ensuite dans les palanquees de
--  plusieurs fiches de securite successives sans ressaisir le
--  roster a chaque plongee. Independant de seance/fiche_securite :
--  composer une palanquee a partir d'un groupe recopie ses membres,
--  le groupe n'est pas modifie par la suite.
-- ============================================================

CREATE TABLE groupe_plongeurs (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nom             VARCHAR(120) NOT NULL,
    saison_id       BIGINT NOT NULL REFERENCES saison(id),
    date_creation   DATE NOT NULL
);

CREATE TABLE membre_groupe_plongeurs (
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    groupe_id              BIGINT NOT NULL REFERENCES groupe_plongeurs(id) ON DELETE CASCADE,
    eleve_id               BIGINT REFERENCES eleve(id),
    utilisateur_id         BIGINT REFERENCES utilisateur(id),
    nom                    VARCHAR(120) NOT NULL,
    prenom                 VARCHAR(120) NOT NULL,
    aptitude               VARCHAR(120),
    qualification_preparee VARCHAR(120)
);
