-- ============================================================
--  Suivi des formations de plongee - schema initial
--  Compatible PostgreSQL 14+ et H2 (MODE=PostgreSQL)
-- ============================================================

-- ---------- Identites et droits ----------

CREATE TABLE utilisateur (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email           VARCHAR(180) NOT NULL UNIQUE,
    mot_de_passe    VARCHAR(100) NOT NULL,
    nom             VARCHAR(80)  NOT NULL,
    prenom          VARCHAR(80)  NOT NULL,
    actif           BOOLEAN      NOT NULL DEFAULT TRUE,
    -- NULL pour un administratif, renseigne pour un encadrant
    niveau_encadrement VARCHAR(2),
    numero_licence  VARCHAR(30),
    cree_le         TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_niveau_encadrement CHECK (niveau_encadrement IN ('E1','E2','E3','E4'))
);

CREATE TABLE utilisateur_role (
    utilisateur_id BIGINT NOT NULL REFERENCES utilisateur(id) ON DELETE CASCADE,
    role           VARCHAR(20) NOT NULL,
    PRIMARY KEY (utilisateur_id, role),
    CONSTRAINT ck_role CHECK (role IN ('ADMIN','MONITEUR','ELEVE'))
);

CREATE TABLE refresh_token (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    utilisateur_id BIGINT      NOT NULL REFERENCES utilisateur(id) ON DELETE CASCADE,
    empreinte      VARCHAR(64) NOT NULL UNIQUE,   -- SHA-256 du token, jamais le token en clair
    expire_le      TIMESTAMP   NOT NULL,
    revoque        BOOLEAN     NOT NULL DEFAULT FALSE
);
CREATE INDEX idx_refresh_utilisateur ON refresh_token(utilisateur_id);

-- ---------- Referentiel MFT ----------

-- Un referentiel = un niveau + une version datee du MFT.
-- Un cursus est fige sur un referentiel : une revision du MFT
-- ne modifie jamais retroactivement une formation en cours.
CREATE TABLE referentiel (
    id                        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    niveau                    VARCHAR(4)  NOT NULL,
    version_mft               VARCHAR(40) NOT NULL,
    date_application          DATE        NOT NULL,
    source                    VARCHAR(255),
    actif                     BOOLEAN     NOT NULL DEFAULT TRUE,
    -- regles de delivrance, en donnees et non en dur
    age_minimum               INT         NOT NULL,
    niveau_prerequis          VARCHAR(4),
    qualification_requise     VARCHAR(20),
    milieu_naturel_exclusif   BOOLEAN     NOT NULL DEFAULT FALSE,
    niveau_encadrant_validation VARCHAR(2) NOT NULL,
    niveau_encadrant_delivrance VARCHAR(2) NOT NULL,
    profondeur_max_validation INT         NOT NULL,
    profondeur_max_formation  INT         NOT NULL,
    prerogative_profondeur    INT         NOT NULL,
    CONSTRAINT ck_ref_niveau CHECK (niveau IN ('N1','N2','N3')),
    CONSTRAINT uq_referentiel UNIQUE (niveau, version_mft)
);

CREATE TABLE bloc_competence (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    referentiel_id   BIGINT      NOT NULL REFERENCES referentiel(id) ON DELETE CASCADE,
    code             VARCHAR(4)  NOT NULL,     -- C1 .. C9, commun aux trois niveaux
    intitule         VARCHAR(200) NOT NULL,    -- mais l'intitule varie selon le niveau
    ordre            INT         NOT NULL,
    -- C8 : connaissances verifiees au fil des autres competences, pas en seance dediee
    evaluation_transverse BOOLEAN NOT NULL DEFAULT FALSE,
    -- C6 du N2 : doit etre validee en fin de formation
    valider_en_dernier    BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT uq_bloc UNIQUE (referentiel_id, code)
);

CREATE TABLE critere (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bloc_id       BIGINT NOT NULL REFERENCES bloc_competence(id) ON DELETE CASCADE,
    ordre         INT    NOT NULL,
    savoir_faire  VARCHAR(400) NOT NULL,
    critere_realisation TEXT,
    commentaire   TEXT,
    CONSTRAINT uq_critere UNIQUE (bloc_id, ordre)
);

-- ---------- Formation ----------

CREATE TABLE saison (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    libelle     VARCHAR(20) NOT NULL UNIQUE,
    date_debut  DATE NOT NULL,
    date_fin    DATE NOT NULL,
    ouverte     BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE eleve (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nom                     VARCHAR(80) NOT NULL,
    prenom                  VARCHAR(80) NOT NULL,
    date_naissance          DATE,
    numero_licence          VARCHAR(30),
    -- donnee de sante : on ne stocke que la date de fin de validite,
    -- jamais le certificat lui-meme
    certificat_valide_jusqu_au DATE,
    autorisation_legale     BOOLEAN NOT NULL DEFAULT FALSE,
    utilisateur_id          BIGINT REFERENCES utilisateur(id) ON DELETE SET NULL,
    archive_le              TIMESTAMP
);

CREATE TABLE qualification (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    eleve_id       BIGINT NOT NULL REFERENCES eleve(id) ON DELETE CASCADE,
    type           VARCHAR(20) NOT NULL,   -- N1, N2, N3, RIFAP, PE40, PA20, NITROX...
    date_obtention DATE NOT NULL,
    expire_le      DATE,
    CONSTRAINT uq_qualification UNIQUE (eleve_id, type)
);

CREATE TABLE cursus (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    eleve_id             BIGINT NOT NULL REFERENCES eleve(id),
    saison_id            BIGINT NOT NULL REFERENCES saison(id),
    referentiel_id       BIGINT NOT NULL REFERENCES referentiel(id),
    moniteur_referent_id BIGINT REFERENCES utilisateur(id),
    statut               VARCHAR(20) NOT NULL DEFAULT 'EN_COURS',
    ouvert_le            DATE NOT NULL DEFAULT CURRENT_DATE,
    CONSTRAINT ck_cursus_statut CHECK (statut IN ('EN_COURS','VALIDE','DELIVRE','SUSPENDU','ABANDON')),
    CONSTRAINT uq_cursus UNIQUE (eleve_id, saison_id, referentiel_id)
);
CREATE INDEX idx_cursus_saison ON cursus(saison_id);

CREATE TABLE seance (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    saison_id   BIGINT NOT NULL REFERENCES saison(id),
    date_seance DATE   NOT NULL,
    milieu      VARCHAR(12) NOT NULL,   -- ARTIFICIEL (piscine, fosse) ou NATUREL
    lieu        VARCHAR(120),
    profondeur_max INT,
    dp_id       BIGINT REFERENCES utilisateur(id),
    commentaire TEXT,
    CONSTRAINT ck_milieu CHECK (milieu IN ('ARTIFICIEL','NATUREL'))
);
CREATE INDEX idx_seance_date ON seance(date_seance);

CREATE TABLE participation (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cursus_id  BIGINT NOT NULL REFERENCES cursus(id) ON DELETE CASCADE,
    seance_id  BIGINT NOT NULL REFERENCES seance(id) ON DELETE CASCADE,
    statut     VARCHAR(12) NOT NULL,   -- PRESENT, ABSENT, EXCUSE
    atelier    VARCHAR(12),            -- NAGE, BLOC, THEORIE, PLONGEE
    commentaire TEXT,
    CONSTRAINT ck_presence CHECK (statut IN ('PRESENT','ABSENT','EXCUSE')),
    CONSTRAINT ck_atelier  CHECK (atelier IN ('NAGE','BLOC','THEORIE','PLONGEE')),
    CONSTRAINT uq_participation UNIQUE (cursus_id, seance_id)
);

-- ---------- Evaluation ----------

-- Table en ajout seul : on n'ecrase jamais une ligne.
-- L'etat courant d'un critere est l'evaluation la plus recente.
CREATE TABLE evaluation (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cursus_id   BIGINT NOT NULL REFERENCES cursus(id) ON DELETE CASCADE,
    critere_id  BIGINT NOT NULL REFERENCES critere(id),
    seance_id   BIGINT REFERENCES seance(id),
    moniteur_id BIGINT NOT NULL REFERENCES utilisateur(id),
    statut      VARCHAR(20) NOT NULL,
    commentaire TEXT,
    date_evaluation DATE      NOT NULL,
    saisi_le    TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_statut_acquisition CHECK (statut IN ('NON_ABORDE','EN_COURS','ACQUIS'))
);
CREATE INDEX idx_evaluation_cursus  ON evaluation(cursus_id, critere_id, saisi_le DESC);
CREATE INDEX idx_evaluation_moniteur ON evaluation(moniteur_id);

CREATE TABLE validation_competence (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cursus_id    BIGINT NOT NULL REFERENCES cursus(id) ON DELETE CASCADE,
    bloc_id      BIGINT NOT NULL REFERENCES bloc_competence(id),
    moniteur_id  BIGINT NOT NULL REFERENCES utilisateur(id),
    date_validation DATE NOT NULL,
    commentaire  TEXT,
    CONSTRAINT uq_validation UNIQUE (cursus_id, bloc_id)
);

CREATE TABLE delivrance (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cursus_id       BIGINT NOT NULL UNIQUE REFERENCES cursus(id),
    delivre_par_id  BIGINT NOT NULL REFERENCES utilisateur(id),
    date_delivrance DATE   NOT NULL,
    numero_brevet   VARCHAR(40),
    -- N1 obtenu en milieu artificiel : 4 plongees en milieu naturel
    -- a attester dans les 12 mois
    plongees_milieu_naturel_a_faire INT NOT NULL DEFAULT 0,
    echeance_plongees DATE
);

-- ---------- Journal d'audit ----------

CREATE TABLE journal_audit (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    horodatage  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    acteur      VARCHAR(180),
    action      VARCHAR(60) NOT NULL,
    entite      VARCHAR(60),
    entite_id   BIGINT,
    detail      TEXT
);
CREATE INDEX idx_audit_horodatage ON journal_audit(horodatage DESC);
