-- ============================================================
--  Progression type : l'annee de formation d'un niveau decoupee en
--  periodes (plages de mois), chacune avec les blocs du referentiel qui
--  y sont travailles. Rattachee a une version du referentiel et non au
--  niveau : les blocs changent d'une revision du MFT a l'autre.
--
--  Les periodes sont exprimees en mois (1 = janvier ... 12 = decembre)
--  et non en dates : la meme progression resert d'une saison a l'autre.
--  Une periode peut enjamber le changement d'annee (mois_debut = 11,
--  mois_fin = 2 : novembre a fevrier).
--
--  Un bloc supprime du referentiel disparait des periodes (ON DELETE
--  CASCADE) ; un referentiel supprime emporte ses progressions.
-- ============================================================

CREATE TABLE progression_type (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    referentiel_id  BIGINT NOT NULL REFERENCES referentiel(id) ON DELETE CASCADE,
    nom             VARCHAR(120) NOT NULL,
    description     TEXT
);

CREATE TABLE periode_progression (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    progression_id  BIGINT NOT NULL REFERENCES progression_type(id) ON DELETE CASCADE,
    rang            INTEGER NOT NULL,
    intitule        VARCHAR(200) NOT NULL,
    mois_debut      INTEGER NOT NULL CHECK (mois_debut BETWEEN 1 AND 12),
    mois_fin        INTEGER NOT NULL CHECK (mois_fin BETWEEN 1 AND 12),
    -- ARTIFICIEL / NATUREL ; NULL = indifferent
    milieu          VARCHAR(20),
    note            TEXT
);

CREATE TABLE periode_progression_bloc (
    periode_id      BIGINT NOT NULL REFERENCES periode_progression(id) ON DELETE CASCADE,
    bloc_id         BIGINT NOT NULL REFERENCES bloc_competence(id) ON DELETE CASCADE,
    PRIMARY KEY (periode_id, bloc_id)
);
