-- ============================================================
--  Planning du bassin, lot 1 : espaces et groupes d'entrainement.
--
--  espace_bassin : les lignes d'eau de la piscine et la fosse, la ou un
--  groupe peut etre place un soir d'entrainement. capacite et
--  profondeur_max sont indicatives (avertissements du planning, pas de
--  refus) ; NULL = sans objet ou inconnue.
--
--  groupe_entrainement : groupe de la saison (Debutants, Perfect N1,
--  Prepa N2...), avec ses encadrants attitres, sa ligne d'eau attitree et
--  ses eleves, ranges par l'admin. Sans rapport avec groupe_plongeurs
--  (V13), qui compose les palanquees d'un sejour. niveau_prepare (N1/N2/N3)
--  sert seulement a suggerer le groupe d'un eleve d'apres son cursus en
--  cours ; NULL pour un groupe sans formation (Perfect N1, N2+).
--
--  Un eleve est dans au plus un groupe par saison : regle tenue par
--  GroupeEntrainementService (la saison n'est pas une colonne de la table
--  de liaison).
-- ============================================================

CREATE TABLE espace_bassin (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nom             VARCHAR(60) NOT NULL,
    type            VARCHAR(10) NOT NULL CHECK (type IN ('LIGNE', 'FOSSE')),
    ordre           INTEGER NOT NULL,
    profondeur_max  INTEGER,
    capacite        INTEGER,
    actif           BOOLEAN NOT NULL DEFAULT TRUE
);

-- Bassin du club : six lignes d'eau et la fosse a 10 m (15 plongeurs
-- encadrants compris), d'apres le planning septembre-decembre 2026.
INSERT INTO espace_bassin (nom, type, ordre, profondeur_max, capacite) VALUES
 ('Ligne 1', 'LIGNE', 1, NULL, NULL),
 ('Ligne 2', 'LIGNE', 2, NULL, NULL),
 ('Ligne 3', 'LIGNE', 3, NULL, NULL),
 ('Ligne 4', 'LIGNE', 4, NULL, NULL),
 ('Ligne 5', 'LIGNE', 5, NULL, NULL),
 ('Ligne 6', 'LIGNE', 6, NULL, NULL),
 ('Fosse',   'FOSSE', 7, 10,   15);

CREATE TABLE groupe_entrainement (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    saison_id          BIGINT NOT NULL REFERENCES saison(id) ON DELETE CASCADE,
    nom                VARCHAR(80) NOT NULL,
    ordre              INTEGER NOT NULL,
    niveau_prepare     VARCHAR(2) CHECK (niveau_prepare IN ('N1', 'N2', 'N3')),
    espace_attitre_id  BIGINT REFERENCES espace_bassin(id) ON DELETE SET NULL
);

CREATE TABLE groupe_entrainement_encadrant (
    groupe_id       BIGINT NOT NULL REFERENCES groupe_entrainement(id) ON DELETE CASCADE,
    utilisateur_id  BIGINT NOT NULL REFERENCES utilisateur(id) ON DELETE CASCADE,
    PRIMARY KEY (groupe_id, utilisateur_id)
);

CREATE TABLE groupe_entrainement_eleve (
    groupe_id  BIGINT NOT NULL REFERENCES groupe_entrainement(id) ON DELETE CASCADE,
    eleve_id   BIGINT NOT NULL REFERENCES eleve(id) ON DELETE CASCADE,
    PRIMARY KEY (groupe_id, eleve_id)
);
