-- ============================================================
--  Planning du bassin, lot 2 : ou est chaque groupe, soir par soir.
--
--  Une "soiree" est une date de la saison qui porte des seances (le lundi
--  soir, piscine et fosse a la meme heure). Rien n'est stocke tant que le
--  groupe est a sa ligne attitree : affectation_groupe ne garde que les
--  ecarts (autre ligne, fosse, fosse limitee, activite, absence), de sorte
--  que changer la ligne attitree d'un groupe suit sur toutes les dates non
--  retouchees.
--
--  soiree_planning : le responsable de seance du soir (distinct du DP de la
--  fiche de securite, qui reste choisi a part, E3 minimum) et une note.
-- ============================================================

CREATE TABLE affectation_groupe (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    groupe_id          BIGINT NOT NULL REFERENCES groupe_entrainement(id) ON DELETE CASCADE,
    date_soiree        DATE NOT NULL,
    -- ESPACE : espace_id renseigne ; ACTIVITE : activite renseignee ; ABSENT : ni l'un ni l'autre
    type               VARCHAR(10) NOT NULL CHECK (type IN ('ESPACE', 'ACTIVITE', 'ABSENT')),
    espace_id          BIGINT REFERENCES espace_bassin(id) ON DELETE CASCADE,
    -- Fosse limitee (F6 = 6) ; NULL = profondeur de l'espace
    profondeur_limitee INTEGER,
    activite           VARCHAR(80),
    CONSTRAINT uq_affectation_groupe UNIQUE (groupe_id, date_soiree)
);

CREATE TABLE soiree_planning (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    saison_id       BIGINT NOT NULL REFERENCES saison(id) ON DELETE CASCADE,
    date_soiree     DATE NOT NULL,
    responsable_id  BIGINT REFERENCES utilisateur(id) ON DELETE SET NULL,
    note            VARCHAR(200),
    CONSTRAINT uq_soiree_planning UNIQUE (saison_id, date_soiree)
);
