-- ============================================================
--  Planning du bassin, lot 3 : qui vient quel soir.
--
--  Chaque encadrant repond present ou absent pour une soiree (une date de
--  la saison qui porte des seances). Pas de ligne = pas encore repondu :
--  on ne suppose rien. Un admin peut repondre a la place d'un encadrant
--  (prevenu par telephone), d'ou la trace de qui a saisi.
-- ============================================================

CREATE TABLE disponibilite_encadrant (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    saison_id       BIGINT NOT NULL REFERENCES saison(id) ON DELETE CASCADE,
    date_soiree     DATE NOT NULL,
    utilisateur_id  BIGINT NOT NULL REFERENCES utilisateur(id) ON DELETE CASCADE,
    reponse         VARCHAR(10) NOT NULL CHECK (reponse IN ('PRESENT', 'ABSENT')),
    saisi_par_id    BIGINT REFERENCES utilisateur(id) ON DELETE SET NULL,
    CONSTRAINT uq_disponibilite_encadrant UNIQUE (utilisateur_id, date_soiree)
);

CREATE INDEX ix_disponibilite_saison ON disponibilite_encadrant (saison_id);
