-- ============================================================
--  Materiel du club (blocs, detendeurs, gilets stabilisateurs,
--  combinaisons) et prets pour les sorties, geres par le directeur
--  technique.
--
--  Cadre reglementaire retenu :
--  - Detendeurs, gilets et combinaisons pretes aux membres sont traites
--    comme des EPI d'occasion (position FFESSM, juillet 2018). Code du
--    sport, art. A322-177 : une fiche de gestion par equipement, conservee
--    trois ans apres la mise au rebut ; son contenu est fixe par l'annexe
--    III-27 : reference precise, notice du fabricant, date d'achat ou de
--    mise en service, date prevue de mise au rebut (EPI sujets au
--    vieillissement), organisation du maintien en conformite, reparations,
--    incidents, remplacement d'elements interchangeables, mesures
--    d'hygiene et de desinfection, date effective de mise au rebut.
--    D'ou : les colonnes de equipement, et le journal intervention_equipement.
--  - Art. A322-81 : materiel regulierement verifie et entretenu ; tubas et
--    detendeurs desinfectes avant chaque plongee en cas de changement
--    d'utilisateur (une ligne DESINFECTION a chaque pret d'un detendeur).
--  - Blocs : equipements sous pression, arrete du 20 novembre 2017.
--    Inspection periodique (TIV) au plus tous les 12 mois ; requalification
--    tous les 6 ans sous le regime TIV, 2 ans sinon (colonne regime_tiv).
--    Periodicites portees par EcheancesEquipement.
--
--  equipement.reference : le marquage du club (B-12, D-03...), unique.
--  Les colonnes propres a un type restent NULL pour les autres.
--
--  intervention_equipement est en AJOUT SEUL, comme evaluation : c'est
--  l'historique exige par l'annexe III-27. Une erreur de saisie se
--  corrige par une nouvelle ligne, jamais par UPDATE ni DELETE.
--
--  pret.emprunteur_nom garde le nom tel qu'au moment du pret : le lien
--  vers l'eleve ou l'encadrant peut disparaitre (suppression d'un eleve
--  archive, d'un compte), la tracabilite du materiel doit rester.
-- ============================================================

ALTER TABLE utilisateur_role DROP CONSTRAINT ck_role;
ALTER TABLE utilisateur_role ADD CONSTRAINT ck_role
    CHECK (role IN ('ADMIN', 'MONITEUR', 'ELEVE', 'DIRECTEUR_TECHNIQUE'));

CREATE TABLE equipement (
    id                         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type                       VARCHAR(12)  NOT NULL CHECK (type IN ('BLOC', 'DETENDEUR', 'GILET', 'COMBINAISON')),
    reference                  VARCHAR(30)  NOT NULL,
    marque                     VARCHAR(80),
    modele                     VARCHAR(80),
    numero_serie               VARCHAR(60),
    taille                     VARCHAR(20),
    date_fabrication           DATE,
    date_achat                 DATE,
    date_mise_en_service       DATE,
    date_rebut_prevue          DATE,
    -- Notice du fabricant : ou la trouver (classeur, lien, fichier partage).
    notice                     VARCHAR(255),
    -- Organisation du maintien en conformite, d'apres la notice.
    consignes_entretien        TEXT,
    periodicite_revision_mois  INTEGER CHECK (periodicite_revision_mois > 0),
    -- Blocs
    volume_litres              NUMERIC(4,1),
    pression_service_bar       INTEGER,
    pression_epreuve_bar       INTEGER,
    matiere                    VARCHAR(10) CHECK (matiere IN ('ACIER', 'ALUMINIUM')),
    robinetterie               VARCHAR(80),
    date_premiere_epreuve      DATE,
    nitrox                     BOOLEAN NOT NULL DEFAULT FALSE,
    regime_tiv                 BOOLEAN NOT NULL DEFAULT TRUE,
    -- Detendeurs : 1er etage, 2e etage, octopus, manometre (EN 250).
    composition                VARCHAR(255),
    -- Combinaisons
    epaisseur_mm               NUMERIC(3,1),
    hors_service               BOOLEAN NOT NULL DEFAULT FALSE,
    date_rebut                 DATE,
    motif_rebut                VARCHAR(255),
    remarques                  TEXT,
    CONSTRAINT uq_equipement_reference UNIQUE (reference)
);

CREATE TABLE pret (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    eleve_id            BIGINT REFERENCES eleve(id) ON DELETE SET NULL,
    utilisateur_id      BIGINT REFERENCES utilisateur(id) ON DELETE SET NULL,
    emprunteur_nom      VARCHAR(170) NOT NULL,
    seance_id           BIGINT REFERENCES seance(id) ON DELETE SET NULL,
    motif               VARCHAR(120),
    date_pret           DATE NOT NULL,
    date_retour_prevue  DATE,
    date_retour         DATE,
    prete_par_id        BIGINT REFERENCES utilisateur(id) ON DELETE SET NULL,
    recu_par_id         BIGINT REFERENCES utilisateur(id) ON DELETE SET NULL,
    remarques           TEXT
);

CREATE INDEX ix_pret_en_cours ON pret (date_retour);

CREATE TABLE pret_equipement (
    pret_id        BIGINT NOT NULL REFERENCES pret(id) ON DELETE CASCADE,
    equipement_id  BIGINT NOT NULL REFERENCES equipement(id),
    PRIMARY KEY (pret_id, equipement_id)
);

CREATE INDEX ix_pret_equipement_equipement ON pret_equipement (equipement_id);

CREATE TABLE intervention_equipement (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    equipement_id      BIGINT NOT NULL REFERENCES equipement(id),
    type               VARCHAR(20) NOT NULL CHECK (type IN ('INSPECTION_VISUELLE', 'REQUALIFICATION',
                           'REVISION', 'REPARATION', 'REMPLACEMENT_PIECE', 'CONTROLE', 'DESINFECTION', 'INCIDENT')),
    date_intervention  DATE NOT NULL,
    -- TIV (nom, numero), atelier, organisme de requalification...
    intervenant        VARCHAR(120),
    resultat           VARCHAR(12) CHECK (resultat IN ('CONFORME', 'NON_CONFORME')),
    description        TEXT,
    pret_id            BIGINT REFERENCES pret(id) ON DELETE SET NULL,
    saisi_par_id       BIGINT REFERENCES utilisateur(id) ON DELETE SET NULL,
    saisi_le           TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX ix_intervention_equipement ON intervention_equipement (equipement_id);

-- Historique Envers (voir V6) des deux entites modifiables.
CREATE TABLE equipement_aud (
    rev                        INTEGER NOT NULL REFERENCES revision_audit(id),
    revtype                    SMALLINT,
    id                         BIGINT NOT NULL,
    type                       VARCHAR(12),
    reference                  VARCHAR(30),
    marque                     VARCHAR(80),
    modele                     VARCHAR(80),
    numero_serie               VARCHAR(60),
    taille                     VARCHAR(20),
    date_fabrication           DATE,
    date_achat                 DATE,
    date_mise_en_service       DATE,
    date_rebut_prevue          DATE,
    notice                     VARCHAR(255),
    consignes_entretien        TEXT,
    periodicite_revision_mois  INTEGER,
    volume_litres              NUMERIC(4,1),
    pression_service_bar       INTEGER,
    pression_epreuve_bar       INTEGER,
    matiere                    VARCHAR(10),
    robinetterie               VARCHAR(80),
    date_premiere_epreuve      DATE,
    nitrox                     BOOLEAN,
    regime_tiv                 BOOLEAN,
    composition                VARCHAR(255),
    epaisseur_mm               NUMERIC(3,1),
    hors_service               BOOLEAN,
    date_rebut                 DATE,
    motif_rebut                VARCHAR(255),
    remarques                  TEXT,
    PRIMARY KEY (rev, id)
);

CREATE TABLE pret_aud (
    rev                 INTEGER NOT NULL REFERENCES revision_audit(id),
    revtype             SMALLINT,
    id                  BIGINT NOT NULL,
    eleve_id            BIGINT,
    utilisateur_id      BIGINT,
    emprunteur_nom      VARCHAR(170),
    seance_id           BIGINT,
    motif               VARCHAR(120),
    date_pret           DATE,
    date_retour_prevue  DATE,
    date_retour         DATE,
    prete_par_id        BIGINT,
    recu_par_id         BIGINT,
    remarques           TEXT,
    PRIMARY KEY (rev, id)
);
