-- ============================================================
--  Photos du materiel avant et apres un pret : l'etat du materiel a la
--  remise et au retour, pour trancher un litige ou documenter un
--  incident (le journal de l'equipement garde le texte, la photo
--  l'illustre).
--
--  Table separee, comme photo_eleve : les photos n'alourdissent jamais la
--  lecture d'un pret. equipement_id facultatif : une photo peut montrer
--  tout le lot. On photographie le materiel, pas les personnes (le club
--  suit des mineurs, le droit a l'image est un consentement a part).
--
--  Regles tenues par PhotoPretService : photos AVANT tant que le pret est
--  en cours ; photos APRES aussi apres le retour ; suppression seulement
--  tant que le pret est en cours (ensuite, elles font foi). Annuler un
--  pret supprime ses photos (ON DELETE CASCADE).
-- ============================================================

CREATE TABLE photo_pret (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pret_id        BIGINT       NOT NULL REFERENCES pret(id) ON DELETE CASCADE,
    moment         VARCHAR(5)   NOT NULL CHECK (moment IN ('AVANT', 'APRES')),
    equipement_id  BIGINT       REFERENCES equipement(id) ON DELETE SET NULL,
    legende        VARCHAR(120),
    contenu        BYTEA        NOT NULL,
    type_contenu   VARCHAR(30)  NOT NULL CHECK (type_contenu IN ('image/jpeg', 'image/png')),
    prise_le       TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    prise_par_id   BIGINT       REFERENCES utilisateur(id) ON DELETE SET NULL
);

CREATE INDEX ix_photo_pret ON photo_pret (pret_id);
