-- ============================================================
--  Sorties : un week-end en carriere, un sejour en mer... Une sortie
--  porte un nom, un lieu, des dates, et les seances (plongees) choisies
--  par l'admin ou le directeur technique parmi celles de ses dates.
--  Une seance appartient au plus a une sortie.
--
--  Les prets de materiel se rattachent desormais a la sortie entiere
--  (pret.sortie_id) et non plus a une seance : pret.seance_id (V29,
--  jamais utilise en production) disparait.
--
--  La sortie est historisee par Envers (sortie_aud) ; la liaison aux
--  seances ne l'est pas, meme choix que pret_equipement.
-- ============================================================

CREATE TABLE sortie (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nom         VARCHAR(120) NOT NULL,
    lieu        VARCHAR(120),
    date_debut  DATE NOT NULL,
    date_fin    DATE NOT NULL,
    remarques   TEXT,
    CONSTRAINT ck_sortie_dates CHECK (date_fin >= date_debut)
);

CREATE TABLE sortie_seance (
    sortie_id  BIGINT NOT NULL REFERENCES sortie(id) ON DELETE CASCADE,
    seance_id  BIGINT NOT NULL REFERENCES seance(id) ON DELETE CASCADE,
    PRIMARY KEY (sortie_id, seance_id),
    CONSTRAINT uq_sortie_seance UNIQUE (seance_id)
);

CREATE TABLE sortie_aud (
    rev         INTEGER NOT NULL REFERENCES revision_audit(id),
    revtype     SMALLINT,
    id          BIGINT NOT NULL,
    nom         VARCHAR(120),
    lieu        VARCHAR(120),
    date_debut  DATE,
    date_fin    DATE,
    remarques   TEXT,
    PRIMARY KEY (rev, id)
);

ALTER TABLE pret ADD COLUMN sortie_id BIGINT REFERENCES sortie(id);
ALTER TABLE pret DROP COLUMN seance_id;
ALTER TABLE pret_aud ADD COLUMN sortie_id BIGINT;
ALTER TABLE pret_aud DROP COLUMN seance_id;
