-- ============================================================
--  Assistant IA : un administrateur pilote Claude Code depuis
--  l'application pour faire evoluer le code du club (branche,
--  tests, merge sur master, tag de mise en production).
--
--  Le role IA ne se donne qu'a un ADMIN (AdminMoniteurService). La
--  page et l'API n'existent qu'en profil dev : Claude Code tourne sur le
--  poste du developpeur, jamais sur le serveur de production. Les tables
--  sont creees partout pour garder un seul schema, elles restent vides
--  en production.
--
--  journal_ia est en AJOUT SEUL, comme evaluation : chaque message,
--  chaque outil lance par l'assistant, chaque passage de tests, merge,
--  tag et push, avec son auteur et sa date. La preuve qu'un commit a
--  passe les tests (TESTS_OK + commit_sha) est lue dans ce journal avant
--  d'autoriser le merge et le tag.
-- ============================================================

ALTER TABLE utilisateur_role DROP CONSTRAINT ck_role;
ALTER TABLE utilisateur_role ADD CONSTRAINT ck_role
    CHECK (role IN ('ADMIN', 'MONITEUR', 'ELEVE', 'DIRECTEUR_TECHNIQUE', 'IA'));

CREATE TABLE session_ia (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titre             VARCHAR(120) NOT NULL,
    -- Branche de travail (ia/...) et copie de travail git (worktree) dediee.
    branche           VARCHAR(120) NOT NULL UNIQUE,
    dossier           VARCHAR(500) NOT NULL,
    -- Identifiant de conversation Claude Code, repris a chaque message (--resume).
    claude_session_id VARCHAR(36)  NOT NULL,
    cree_par_id       BIGINT       NOT NULL REFERENCES utilisateur(id),
    cree_le           TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE journal_ia (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id  BIGINT       NOT NULL REFERENCES session_ia(id),
    type        VARCHAR(20)  NOT NULL CHECK (type IN ('MESSAGE', 'TEXTE', 'OUTIL', 'OUTIL_ERREUR', 'FIN', 'ERREUR',
                                                     'ARRET', 'TESTS_LANCES', 'TESTS_OK', 'TESTS_KO',
                                                     'MERGE', 'TAG_POUSSE')),
    contenu     TEXT,
    commit_sha  VARCHAR(40),
    -- Nul pour ce qui vient de l'assistant lui-meme.
    auteur_id   BIGINT REFERENCES utilisateur(id),
    cree_le     TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE INDEX ix_journal_ia_session ON journal_ia (session_id, id);
