-- ============================================================
--  Fiche d'evaluation et de suivi d'une bouteille (inspection
--  visuelle par un TIV), reprise de l'onglet du meme nom du
--  classeur « Historique Blocs » et completee d'apres le manuel de
--  formation TIV de la FFESSM (UC8.2, « Rapports d'inspection ») :
--  identification unique du compte rendu (inspection_tiv.id),
--  structure emettrice (le club), bouteille et accessoires, date,
--  observations, nom du TIV, decision (favorable ou defavorable au
--  maintien en service), proprietaire, prochaine echeance
--  reglementaire, marquage de la derniere requalification.
--
--  inspection_tiv complete la ligne INSPECTION_VISUELLE du journal
--  (date, intervenant, resultat, observations), une pour une.
--  Comme le journal, en AJOUT SEUL : une erreur se corrige par une
--  nouvelle inspection. Le proprietaire et les echeances y sont
--  copies : le compte rendu reste tel qu'il a ete emis.
--
--  constat_tiv : une ligne par question de la fiche (liste dans
--  PointInspectionTiv), reponse oui/non, decision, precisions
--  (localisation, mesures, residus, entreprise) et realisation.
-- ============================================================

CREATE TABLE inspection_tiv (
    id                          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    intervention_id             BIGINT       NOT NULL REFERENCES intervention_equipement(id),
    motif                       VARCHAR(25)  NOT NULL
        CHECK (motif IN ('PERIODIQUE', 'AVANT_REQUALIFICATION', 'APRES_INCIDENT', 'AUTRE')),
    tiv_nom                     VARCHAR(120) NOT NULL,
    tiv_numero                  VARCHAR(30)  NOT NULL,
    proprietaire                VARCHAR(80),
    filetage_bouteille          VARCHAR(30),
    filetage_robinet            VARCHAR(30),
    marquage_requalification    VARCHAR(80),
    decision                    VARCHAR(12)  NOT NULL CHECK (decision IN ('FAVORABLE', 'DEFAVORABLE', 'REBUT')),
    prochaine_inspection        DATE,
    prochaine_requalification   DATE,
    CONSTRAINT uq_inspection_tiv_intervention UNIQUE (intervention_id)
);

CREATE TABLE constat_tiv (
    inspection_id   BIGINT       NOT NULL REFERENCES inspection_tiv(id),
    ordre           INTEGER      NOT NULL,
    point           VARCHAR(40)  NOT NULL,
    reponse         BOOLEAN      NOT NULL,
    decision        VARCHAR(255),
    precisions      VARCHAR(255),
    realise_le      DATE,
    PRIMARY KEY (inspection_id, ordre)
);
