-- ============================================================
--  Programme d'exercices d'une seance : une liste ordonnee
--  d'exercices preparee par un moniteur (« vidage de masque en
--  pleine eau », « remontee assistee »...). Un exercice vise une
--  formation (une version du MFT, referentiel_id) et les criteres
--  de celle-ci qu'il fait travailler ; sans formation, c'est un
--  exercice commun (echauffement, nage) qui ne renvoie a aucun
--  critere. La fiche de suivi d'un eleve present affiche les
--  exercices de la seance et marque les criteres travailles.
--
--  Le programme se remplace d'un bloc a chaque enregistrement :
--  ce n'est pas une trace (l'evaluation, elle, l'est), donc pas
--  d'historique Envers. Il disparait avec sa seance ; un critere
--  retire du referentiel sort simplement des exercices.
-- ============================================================

CREATE TABLE exercice_seance (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    seance_id       BIGINT NOT NULL REFERENCES seance(id) ON DELETE CASCADE,
    referentiel_id  BIGINT REFERENCES referentiel(id) ON DELETE CASCADE,
    ordre           INT NOT NULL,
    intitule        VARCHAR(200) NOT NULL,
    consignes       TEXT,
    duree_minutes   INT,
    CONSTRAINT ck_exercice_seance_duree CHECK (duree_minutes IS NULL OR duree_minutes > 0)
);

CREATE INDEX ix_exercice_seance_seance ON exercice_seance(seance_id);

CREATE TABLE exercice_seance_critere (
    exercice_id  BIGINT NOT NULL REFERENCES exercice_seance(id) ON DELETE CASCADE,
    critere_id   BIGINT NOT NULL REFERENCES critere(id) ON DELETE CASCADE,
    PRIMARY KEY (exercice_id, critere_id)
);
