-- ============================================================
--  Planning du bassin : un soir donne, un encadrant peut encadrer
--  un autre groupe que ses groupes attitres (remplacer un collegue
--  absent, renforcer un groupe nombreux...).
--
--  Comme affectation_groupe, on ne garde que l'ecart : pas de ligne =
--  l'encadrant est avec ses groupes attitres. Une ligne le met ce
--  soir-la dans le groupe indique, et seulement dans celui-ci.
--  saisi_par_id garde qui a fait le changement.
-- ============================================================

CREATE TABLE affectation_encadrant (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    saison_id       BIGINT NOT NULL REFERENCES saison(id) ON DELETE CASCADE,
    date_soiree     DATE NOT NULL,
    utilisateur_id  BIGINT NOT NULL REFERENCES utilisateur(id) ON DELETE CASCADE,
    groupe_id       BIGINT NOT NULL REFERENCES groupe_entrainement(id) ON DELETE CASCADE,
    saisi_par_id    BIGINT REFERENCES utilisateur(id) ON DELETE SET NULL,
    CONSTRAINT uq_affectation_encadrant UNIQUE (utilisateur_id, date_soiree)
);

CREATE INDEX ix_affectation_encadrant_saison ON affectation_encadrant (saison_id);
