-- ============================================================
--  Fiches de securite : lier des seances du meme jour (deux bateaux,
--  deux sites a la meme heure...) qui se partagent les plongeurs d'un
--  meme groupe. Sur la fiche d'une seance liee, le groupe ne propose
--  plus que les plongeurs qui ne sont encore dans aucune palanquee des
--  fiches liees.
--
--  Une liaison regroupe deux seances ou plus ; une seance appartient
--  au plus a une liaison. Pas d'historique Envers : comme sortie_seance,
--  c'est un simple rangement, sans decision a tracer.
-- ============================================================

CREATE TABLE liaison_seances (
    id  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
);

CREATE TABLE liaison_seances_seance (
    liaison_id  BIGINT NOT NULL REFERENCES liaison_seances(id) ON DELETE CASCADE,
    seance_id   BIGINT NOT NULL REFERENCES seance(id) ON DELETE CASCADE,
    PRIMARY KEY (liaison_id, seance_id),
    CONSTRAINT uq_liaison_seances_seance UNIQUE (seance_id)
);
