-- ============================================================
--  Reinitialisation de mot de passe (mot de passe oublie, et
--  invitation d'un moniteur cree par un ADMIN).
-- ============================================================

CREATE TABLE reinitialisation_mot_de_passe (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    utilisateur_id BIGINT      NOT NULL REFERENCES utilisateur(id) ON DELETE CASCADE,
    jeton_hash     VARCHAR(64) NOT NULL UNIQUE,   -- SHA-256 du jeton, jamais le jeton en clair
    demandee_le    TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    expire_le      TIMESTAMP   NOT NULL,
    utilisee_le    TIMESTAMP
);
CREATE INDEX idx_reinitialisation_utilisateur ON reinitialisation_mot_de_passe(utilisateur_id);
