-- ============================================================
--  Base d'exercices par competence (choix du club, 2026).
--
--  Chaque competence (bloc) d'une version du MFT recoit une liste
--  d'exercices types, ranges en trois phases : initiation (x.1 a
--  x.3), perfectionnement (x.4 a x.6) et maitrise (x.7 a x.9).
--  Contenu initial du N1 PE20 dans V51 ; ensuite la base se modifie
--  depuis l'ecran /admin/exercices.
--
--  - Un exercice du programme d'une seance peut venir de la base
--    (exercice_seance.exercice_competence_id) : il en garde le lien
--    meme si l'intitule est retouche dans le programme.
--  - Une evaluation porte l'exercice sur lequel le critere a ete
--    note (evaluation.exercice_id, facultatif). Regle du serveur :
--    un critere d'une competence qui a des exercices ne passe a
--    « acquis » que sur un exercice de maitrise.
--  - Un exercice deja note ne se supprime pas (la table evaluation
--    est en ajout seul) : on le desactive.
-- ============================================================

CREATE TABLE exercice_competence (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bloc_id           BIGINT NOT NULL REFERENCES bloc_competence(id) ON DELETE CASCADE,
    numero            VARCHAR(10)  NOT NULL,
    ordre             INT          NOT NULL,
    phase             VARCHAR(20)  NOT NULL,
    intitule          VARCHAR(200) NOT NULL,
    deroulement       TEXT,
    critere_reussite  TEXT,
    actif             BOOLEAN      NOT NULL DEFAULT TRUE,
    CONSTRAINT uq_exercice_competence_numero UNIQUE (bloc_id, numero),
    CONSTRAINT ck_exercice_competence_phase
        CHECK (phase IN ('INITIATION', 'PERFECTIONNEMENT', 'MAITRISE'))
);

CREATE INDEX ix_exercice_competence_bloc ON exercice_competence(bloc_id);

ALTER TABLE exercice_seance
    ADD COLUMN exercice_competence_id BIGINT REFERENCES exercice_competence(id) ON DELETE SET NULL;

ALTER TABLE evaluation
    ADD COLUMN exercice_id BIGINT REFERENCES exercice_competence(id);

CREATE INDEX ix_evaluation_exercice ON evaluation(exercice_id);
