-- ============================================================
--  Base d'exercices du N1 (MFT PE20, decembre 2025) : 10 competences,
--  9 exercices chacune (3 d'initiation, 3 de perfectionnement, 3 de
--  maitrise), d'apres le document du club « Niveau 1 FFESSM -
--  Exercices par competence » (octobre 2026).
--
--  Les numeros sont ceux du document. Attention : le document
--  numerote « 9 » Retourner en surface et « 10 » Evoluer en securite,
--  alors que le referentiel PE20 (V7) les range dans l'ordre inverse
--  (bloc 9 = Evoluer en securite, bloc 10 = Retourner en surface) :
--  le rattachement se fait sur l'ordre du bloc, d'ou la correspondance
--  ci-dessous. Le bloc 11 (connaissances theoriques, transverse) n'a
--  pas d'exercice propre.
--
--  Ensuite, la base se modifie depuis l'ecran /admin/exercices : ne
--  pas retoucher ce fichier une fois applique.
-- ============================================================

INSERT INTO exercice_competence (bloc_id, numero, ordre, phase, intitule, deroulement, critere_reussite)
SELECT b.id, v.numero, v.ordre, v.phase, v.intitule, v.deroulement, v.critere_reussite
  FROM bloc_competence b
  JOIN referentiel r ON r.id = b.referentiel_id
  JOIN (VALUES
    -- ---------- Competence 1 : S'equiper et se desequiper (bloc 1) ----------
    (1, '1.1', 1, 'INITIATION', 'Gréage guidé',
     'Bord de bassin. Démonstration commentée, puis l''élève grée à côté du moniteur : bloc (date, robinet, joint), gilet (dosseret au niveau du robinet), détendeur (2e étage à droite), ouverture lente et lecture du manomètre, tests des détendeurs, de l''inflateur et des purges. Dégréage dans l''ordre inverse.',
     'L''élève cite et fait les 5 vérifications dans l''ordre.'),
    (1, '1.2', 2, 'INITIATION', 'Capelage au sec et vérification croisée',
     'Élèves assis par deux. Capelage, le binôme stabilise le bloc. Vérification croisée : gilet branché, lest, air ouvert, sangles, masque et palmes. Décapelage, bloc reposé couché.',
     'Vérification croisée complète, sans oubli.'),
    (1, '1.3', 3, 'INITIATION', 'Sécurité et hygiène du matériel',
     'Au bord. Règle « bloc debout = bloc tenu, sinon couché », transport du bloc, rinçage, désinfection de l''embout, signalement d''une anomalie au moniteur.',
     'La règle du bloc est appliquée sans rappel pendant toute la séance.'),
    (1, '1.4', 4, 'PERFECTIONNEMENT', 'Test du lestage',
     'Surface, gilet vide, élève vertical, sans palmer. Poumons pleins : l''eau doit arriver aux yeux. À l''expiration, il doit descendre lentement. Ajouter ou retirer 1 kg et recommencer ; confirmer en fin de plongée au palier.',
     'Lestage trouvé, expliqué et noté au carnet.'),
    (1, '1.5', 5, 'PERFECTIONNEMENT', 'Capelage et décapelage dans l''eau',
     'Petit fond puis grand fond, gilet bien gonflé, détendeur en bouche. Glisser les bras dans les bretelles, basculer le bloc, serrer les sangles. Décapelage : une main reste sur le gilet.',
     'Réalisé en grand fond, calmement, sans lâcher le gilet.'),
    (1, '1.6', 6, 'PERFECTIONNEMENT', 'Équipement en conditions réelles',
     'Simulation de bateau : espace réduit, matériel rangé, consignes du DP. L''élève grée, s''équipe et fait la vérification croisée dans le temps imparti.',
     'Prêt à l''heure donnée, sans erreur ni rappel.'),
    (1, '1.7', 7, 'MAITRISE', 'Gréage avec anomalie cachée',
     'Le moniteur prépare un équipement avec une anomalie : inflateur débranché, robinet fermé, joint absent. L''élève grée seul, le moniteur observe sans intervenir.',
     'Anomalie détectée et signalée avant la mise à l''eau.'),
    (1, '1.8', 8, 'MAITRISE', 'Déséquipement et rééquipement en surface',
     'Grand fond. L''élève décapelle, passe son bloc à un équipier, le récupère et recapelle.',
     'Sans aide, calme, une main toujours sur le gilet.'),
    (1, '1.9', 9, 'MAITRISE', 'Matériel personnel et lestage adapté',
     'L''élève présente son masque, ses palmes et sa combinaison, puis adapte son lestage à un changement annoncé (eau douce vers eau salée, combinaison plus épaisse). Rinçage du matériel après la séance.',
     'Explications justes, lestage ajusté dans le bon sens.'),

    -- ---------- Competence 2 : Se mettre a l'eau et sortir de l'eau (bloc 2) ----------
    (2, '2.1', 1, 'INITIATION', 'Entrées en PMT',
     'Bord bas du grand bain, palmes, masque et tuba. Saut droit puis bascule arrière depuis la position accroupie. Signe OK aussitôt en surface.',
     'Masque gardé, signe OK donné sans rappel.'),
    (2, '2.2', 2, 'INITIATION', 'Saut droit en scaphandre',
     'Bord de grand bain (≥ 2,5 m), gilet légèrement gonflé. Vérifier la zone, une main sur masque et détendeur, l''autre sur le lest, regard à l''horizon, grand pas. Dégager la zone.',
     'Matériel en place, zone dégagée pour le suivant.'),
    (2, '2.3', 3, 'INITIATION', 'Bascule arrière progressive',
     'Accroupi au bord, puis assis. Vérifier derrière soi, main droite sur masque et détendeur, main gauche sur les flexibles, menton rentré, bascule groupée au signal.',
     'Bascule groupée, sans hésitation, au signal.'),
    (2, '2.4', 4, 'PERFECTIONNEMENT', 'Entrées depuis une hauteur réelle',
     'Bascule depuis un plot ou un boudin, saut droit depuis une barge ou un plongeoir bas. Regroupement à un point désigné après l''entrée.',
     'Entrée maîtrisée et regroupement immédiat.'),
    (2, '2.5', 5, 'PERFECTIONNEMENT', 'Départ plage',
     'Plage ou mise à l''eau en pente. Entrer jusqu''à mi-cuisse, chausser les palmes en s''appuyant sur le binôme, reculer ou se coucher sur le dos vers le large.',
     'Aucune chute, entraide spontanée.'),
    (2, '2.6', 6, 'PERFECTIONNEMENT', 'Sortie et passage du bloc',
     'Échelle ou bord simulant un bateau, un élève réceptionne. Gilet gonflé, détendeur en bouche, passer le lest si demandé, puis le bloc-gilet par le robinet, retirer les palmes en tenant l''échelle, monter.',
     'Ordre respecté, main toujours sur le support, attente hors de l''axe.'),
    (2, '2.7', 7, 'MAITRISE', 'Mise à l''eau sur consignes du DP',
     'Simulation complète : palanquées constituées, briefing du DP, ordre de passage, technique imposée (saut ou bascule).',
     'Le DP n''a rien à rappeler.'),
    (2, '2.8', 8, 'MAITRISE', 'Mise à l''eau avec contrainte',
     'Regroupement imposé à un bout ou une bouée dès l''entrée, comme en présence de courant. Entrée rapide à l''annonce, palanquée après palanquée.',
     'Regroupement rapide, aucun plongeur gêné.'),
    (2, '2.9', 9, 'MAITRISE', 'Sortie complète en fin de plongée',
     'Retour au support, tour d''horizon, passage du lest et du bloc, montée à l''échelle, zone d''attente respectée.',
     'Sécurité assurée pour lui et pour les autres.'),

    -- ---------- Competence 3 : Evoluer dans l'eau - S'immerger (bloc 3) ----------
    (3, '3.1', 1, 'INITIATION', 'Équilibrage des oreilles',
     'Au sec, explication du Valsalva. Puis en PMT, descente le long d''un bout jusqu''à 2 m, équilibrage dès le premier mètre et à chaque gêne.',
     'L''élève équilibre sans forcer et remonte s''il n''y arrive pas.'),
    (3, '3.2', 2, 'INITIATION', 'Phoque guidé',
     'Scaphandre, le long d''un bout, moniteur en face. Vertical, purge levée, gilet vidé, expiration lente et complète, descente pieds en premier jusqu''à 3 m.',
     'Descente sans palmer, oreilles équilibrées dès 1 m.'),
    (3, '3.3', 3, 'INITIATION', 'Canard en PMT',
     'Petit bain décomposé, puis grand bain. Nage ventrale, buste plié à 90°, jambes levées hors de l''eau, glisse vers le fond.',
     'Palmes sorties de l''eau, glisse verticale.'),
    (3, '3.4', 4, 'PERFECTIONNEMENT', 'Canard en scaphandre',
     'Grand bain, gilet vidé. Même geste qu''en PMT, palmage seulement après la glisse.',
     'Immersion franche, sans moulinet en surface.'),
    (3, '3.5', 5, 'PERFECTIONNEMENT', 'Phoque sans repère et arrêt à 3 m',
     'Pleine eau, sans bout. Descente en phoque, arrêt et stabilisation à 3 m lus sur l''instrument.',
     'Arrêt à 3 m à ± 1 m, lestage adapté.'),
    (3, '3.6', 6, 'PERFECTIONNEMENT', 'Phoque ou canard sur consigne',
     'Le moniteur annonce la technique en surface, l''élève s''immerge, revient, et l''on alterne au hasard.',
     'Technique juste à chaque annonce.'),
    (3, '3.7', 7, 'MAITRISE', 'Immersion à la commande en palanquée',
     'Palanquée de 2 à 4 élèves en surface. Le GP annonce la technique et fait le signe « descendre ». Regroupement et stabilisation à 3 m près du GP.',
     'Départ immédiat, palanquée regroupée, ± 1 m.'),
    (3, '3.8', 8, 'MAITRISE', 'Enchaînement mise à l''eau et immersion',
     'Bascule ou saut, regroupement, signe du GP, immersion sans attendre.',
     'Enchaînement fluide, sans délai.'),
    (3, '3.9', 9, 'MAITRISE', 'Descente en milieu naturel',
     'Le long du mouillage ou en pleine eau, derrière le GP, jusqu''à la profondeur de la plongée.',
     'Descente maîtrisée, oreilles équilibrées, proche du GP.'),

    -- ---------- Competence 4 : Evoluer dans l'eau - Se propulser (bloc 4) ----------
    (4, '4.1', 1, 'INITIATION', 'Le geste au bord',
     'Assis au bord ou accroché à la goulotte. Palmage jambes tendues, mouvement depuis la hanche, chevilles souples. Explication de l''appui de la palme et du bras de levier.',
     'Mouvement venant de la hanche, sans « vélo ».'),
    (4, '4.2', 2, 'INITIATION', 'Palmage ventral et dorsal en PMT',
     'Longueurs de bassin, une position par longueur, ventilation sur tuba en ventral.',
     'Palmes sous la surface, pas d''éclaboussures.'),
    (4, '4.3', 3, 'INITIATION', 'Palmage de sustentation',
     'Grand bain, vertical. Mains sur la tête, puis hors de l''eau, sur 30 s puis 1 min.',
     'Bouche hors de l''eau, ventilation calme.'),
    (4, '4.4', 4, 'PERFECTIONNEMENT', 'Costal et enchaînement sur 100 m',
     'Ajout du palmage costal, puis 100 m en PMT en changeant de position à chaque longueur.',
     '100 m sans essoufflement, geste propre.'),
    (4, '4.5', 5, 'PERFECTIONNEMENT', 'Nage capelée',
     'Surface, gilet légèrement gonflé, sur le dos ou sur le ventre sur tuba. 25 m, puis 50 m vers un point désigné.',
     'Arrivée sans essoufflement, cap tenu.'),
    (4, '4.6', 6, 'PERFECTIONNEMENT', 'Parcours en immersion',
     '3 à 5 m, cerceaux ou plots, moniteur devant. Palmage horizontal à moins de 2 m du moniteur, passage des cerceaux sans contact.',
     'Assiette horizontale, aucun contact.'),
    (4, '4.7', 7, 'MAITRISE', 'Parcours de surface en PMT',
     'Environ 100 m en changeant de position, terminé par 1 min de sustentation mains hors de l''eau.',
     'Pas d''essoufflement, qualité du geste.'),
    (4, '4.8', 8, 'MAITRISE', 'Retour au bateau en capelé',
     'Environ 50 m en scaphandre vers un point désigné, avec un léger effort à fournir.',
     'L''élève peut parler en arrivant.'),
    (4, '4.9', 9, 'MAITRISE', 'Exploration derrière le GP',
     'Milieu naturel. L''élève suit le GP en respectant la profondeur et la distance, palmage sans contact avec le fond.',
     'Proximité du GP et profondeur tenues toute la plongée.'),

    -- ---------- Competence 5 : Evoluer dans l'eau - Se ventiler (bloc 5) ----------
    (5, '5.1', 1, 'INITIATION', 'Ventilation et vidage du tuba',
     'Petit bain puis nage. Respiration lente, visage dans l''eau. Petit canard, retour, vidage par expiration franche, d''abord statique puis en nage.',
     'Premier souffle après vidage sans toux.'),
    (5, '5.2', 2, 'INITIATION', 'Rythme en immersion',
     'À genoux à 2-3 m, moniteur en face. Inspiration sur 3 s, expiration sur 4 à 5 s, apnée de contrôle de quelques secondes à la demande.',
     'Rythme lent et stable, bulles régulières.'),
    (5, '5.3', 3, 'INITIATION', 'Vidage de masque, paliers 1 à 3',
     'À genoux à 2-3 m. Nez dans l''eau sans masque pendant 30 s, puis masque entrouvert, puis à moitié rempli. Main sur le haut de la jupe, tête vers la surface, souffler par le nez.',
     'Chaque palier réussi 3 fois sans stress.'),
    (5, '5.4', 4, 'PERFECTIONNEMENT', 'Vidage de masque, paliers 4 et 5',
     'Masque complètement rempli puis vidé. Masque retiré, remis, vidé.',
     'Masque vidé en une ou deux expirations, sans précipitation.'),
    (5, '5.5', 5, 'PERFECTIONNEMENT', 'Lâcher et reprise d''embout',
     'À genoux puis stabilisé. Embout retiré avec un filet de bulles, reprise et vidage par expiration, puis par le bouton de surpression, langue en écran. Récupération du détendeur lâché en balayant le bras de la hanche vers l''avant.',
     'Aucune inspiration sans embout, deux techniques maîtrisées.'),
    (5, '5.6', 6, 'PERFECTIONNEMENT', 'Apnées courtes',
     'À 3 m, embout retiré, 3 à 5 m de palmage vers le moniteur. D''abord après une inspiration normale, puis après une expiration normale.',
     'Reprise calme, jamais d''hyperventilation avant.'),
    (5, '5.7', 7, 'MAITRISE', 'Gestes en pleine eau et en déplacement',
     'Vidage de masque et lâcher-reprise d''embout stabilisé en pleine eau, puis en palmant derrière le moniteur.',
     'Gestes réalisés sans arrêt de la palanquée.'),
    (5, '5.8', 8, 'MAITRISE', 'Ventilation sous effort modéré',
     'Palmage contre une résistance (moniteur qui retient l''élève par le gilet) comme face à un léger courant, puis récupération.',
     'Rythme retrouvé rapidement, aucun essoufflement.'),
    (5, '5.9', 9, 'MAITRISE', 'Demandes du GP au cours d''une évolution',
     'En évolution, le GP demande un vidage de masque, une reprise d''embout et une courte apnée, à des moments variés.',
     'Réponse sereine à chaque demande.'),

    -- ---------- Competence 6 : Evoluer dans l'eau - S'equilibrer (bloc 6) ----------
    (6, '6.1', 1, 'INITIATION', 'Flottabilité positive, négative, neutre',
     'En surface : gilet vide puis gonflé, poumons pleins puis vides. L''élève décrit ce qu''il ressent et le relie à la ventilation.',
     'L''élève nomme les trois états et leurs causes.'),
    (6, '6.2', 2, 'INITIATION', 'Pivot sur les palmes',
     'Allongé à 3 m, pointes de palmes au sol, gilet réglé par le moniteur. Inspiration ample : le buste monte ; expiration : il redescend.',
     'L''élève contrôle la montée et la descente du buste.'),
    (6, '6.3', 3, 'INITIATION', 'Gilet le long d''un repère',
     'Bout vertical gradué, repère à 4 m. Petites injections, attendre 3 à 5 s avant de corriger, affiner au poumon ballast.',
     '1 min à ± 1 m sans tenir le bout.'),
    (6, '6.4', 4, 'PERFECTIONNEMENT', 'Gilet en pleine eau',
     'Même exercice que 6.3, sans repère visuel, profondeur lue sur l''instrument.',
     '1 min à ± 1 m.'),
    (6, '6.5', 5, 'PERFECTIONNEMENT', '± 1 m au poumon ballast seul',
     'Stabilisé au gilet à 4 m. Au signe « monter », poumons plus pleins ; au signe « descendre », poumons plus vides, sans toucher au gilet.',
     'Écart contrôlé d''1 m dans les deux sens, sans apnée.'),
    (6, '6.6', 6, 'PERFECTIONNEMENT', 'Équilibre en dynamique, 3 m → 5 m → 3 m',
     'Derrière le moniteur. Injection en descendant pour se restabiliser, purge en remontant.',
     'Ajustements faits sans rappel.'),
    (6, '6.7', 7, 'MAITRISE', 'Équilibre à la demande',
     'Le GP indique une profondeur, l''élève s''y stabilise ; on répète à plusieurs profondeurs.',
     '± 1 m à chaque demande.'),
    (6, '6.8', 8, 'MAITRISE', 'Stabilisation en palanquée',
     'Palier simulé à 3 m, sans repère, élèves côte à côte face au GP.',
     '± 1 m tenu sans gêner les équipiers.'),
    (6, '6.9', 9, 'MAITRISE', 'Exploration avec variations de profondeur',
     'Milieu naturel, parcours qui monte et descend. L''élève ajuste son gilet seul.',
     'Ni contact ni palmage pour compenser un mauvais réglage.'),

    -- ---------- Competence 7 : Respecter le milieu et l'environnement (bloc 7) ----------
    (7, '7.1', 1, 'INITIATION', 'Charte, impacts et dangers du milieu',
     'Au bord, 15 min. Charte internationale du plongeur responsable, impact du plongeur sur la faune et le fond, froid et dangers du milieu.',
     'L''élève cite 3 règles de la Charte et 2 dangers du milieu.'),
    (7, '7.2', 2, 'INITIATION', 'Parcours « zéro contact »',
     'Bassin à 3-4 m, objets posés au fond figurant des éléments fragiles. Stabilisation à 50 cm au-dessus, palmage lent, demi-tour sans contact.',
     'Aucun contact, aucun appui sur le fond.'),
    (7, '7.3', 3, 'INITIATION', 'Palmage qui ne touche pas le fond',
     'Près du fond, palmes au-dessus du niveau du buste ; essai d''un palmage en grenouille ou réduit.',
     'Pas de sédiment soulevé, pas de choc des palmes.'),
    (7, '7.4', 4, 'PERFECTIONNEMENT', 'Stabilisation au-dessus d''un fond de sable',
     'Milieu naturel, 6 m environ. Stabilisation à 50 cm du fond, puis déplacement lent.',
     'Aucun nuage de sédiment derrière l''élève.'),
    (7, '7.5', 5, 'PERFECTIONNEMENT', 'Plongée d''observation commentée',
     'Briefing : 3 espèces à chercher et dangers du site. Plongée lente, le GP montre sans toucher. Débriefing.',
     'L''élève observe sans déranger la faune.'),
    (7, '7.6', 6, 'PERFECTIONNEMENT', 'Reconnaissance et carnet',
     'Après la plongée, l''élève identifie les espèces vues et les espèces à risque du site (urticantes, piquantes), puis les note au carnet.',
     'Espèces courantes et dangers identifiés.'),
    (7, '7.7', 7, 'MAITRISE', 'Plongée d''exploration évaluée',
     'Le GP observe l''élève sur toute la plongée : appuis, contacts, distance à la faune.',
     'Aucun appui, contact ou dérangement.'),
    (7, '7.8', 8, 'MAITRISE', 'Évolution près d''un tombant ou d''un herbier',
     'Passage le long d''une zone fragile, stabilisation et palmage adaptés au relief.',
     'Distance tenue sans toucher la paroi ni l''herbier.'),
    (7, '7.9', 9, 'MAITRISE', 'Débriefing et comportement sur site',
     'L''élève raconte sa plongée, évalue son impact et répond sur le froid et les dangers. Sur le bateau ou le site : déchets, matériel et zones protégées respectés.',
     'Analyse juste et comportement responsable avant, pendant et après.'),

    -- ---------- Competence 8 : Communiquer (bloc 8) ----------
    (8, '8.1', 1, 'INITIATION', 'Jeu des signes au sec',
     'En cercle au bord. Le moniteur montre chaque signe et sa réponse : OK, monter, descendre, ça ne va pas, mi-pression, réserve, panne d''air, essoufflement, froid, fin de plongée ou d''exercice. Puis il signe au hasard, l''élève désigné répond ; puis on inverse.',
     'Les 10 signes faits et compris sans erreur.'),
    (8, '8.2', 2, 'INITIATION', 'Signes en surface',
     'Dans l''eau, même jeu, avec le OK de surface à distance et l''appel à l''aide.',
     'Réponse immédiate et juste.'),
    (8, '8.3', 3, 'INITIATION', 'Signes en immersion statique',
     'À genoux à 3 m. Le moniteur fait un signe, l''élève le reproduit puis donne la réponse attendue.',
     'Signes nets, sans hésitation.'),
    (8, '8.4', 4, 'PERFECTIONNEMENT', 'Questions-réponses avec le manomètre',
     'Stabilisés à 3 m en cercle. Le moniteur demande « OK ? », « pression ? » ; l''élève lit son manomètre et répond.',
     'Réponse dans la seconde, lecture juste.'),
    (8, '8.5', 5, 'PERFECTIONNEMENT', 'Communication dans la palanquée',
     'Un élève reçoit un signe du moniteur et le transmet à son équipier, qui réagit.',
     'Signe transmis sans déformation.'),
    (8, '8.6', 6, 'PERFECTIONNEMENT', 'Signe à l''initiative de l''élève',
     'Parcours à 3-5 m, carte-consigne remise au départ (« signale froid au 2e plot »). L''élève attire l''attention du GP, se place dans son champ de vision, fait le signe.',
     'Signe vu et compris du premier coup.'),
    (8, '8.7', 7, 'MAITRISE', 'Évaluation de la compréhension',
     'Le GP fait les 10 signes dans un ordre aléatoire, en statique puis en déplacement ; l''élève répond ou réagit.',
     '10 signes compris et suivis de la bonne réaction.'),
    (8, '8.8', 8, 'MAITRISE', 'Évaluation de la réalisation',
     'Au cours d''une plongée, l''élève annonce spontanément mi-pression, réserve ou froid au bon moment.',
     'Annonce exacte et prompte, sans questionnement du GP.'),
    (8, '8.9', 9, 'MAITRISE', 'Communication en situation d''incident',
     'Scénario annoncé au briefing : l''élève signale une panne d''air ou un essoufflement, puis suit la procédure du GP.',
     'Signe exact, rapide, et procédure comprise.'),

    -- ---------- Competence « 9 » du document : Retourner en surface (bloc 10 du MFT) ----------
    (10, '9.1', 1, 'INITIATION', 'Comprendre la remontée',
     'Au sec : variations de volume entre 0 et 10 m, surpression pulmonaire, règle « ne jamais bloquer sa respiration ». Préparation de la REC : longue expiration en disant « ouuu ».',
     'L''élève explique pourquoi on expire en remontant.'),
    (10, '9.2', 2, 'INITIATION', 'Remontée contrôlée avec repère',
     'Le long d''un bout de 6 m, moniteur en face. Signe « monter », regard vers la surface, main sur la purge, palmage doux, purges courtes et régulières.',
     'Vitesse régulière, aucune accélération près de la surface.'),
    (10, '9.3', 3, 'INITIATION', 'Tour d''horizon et gonflage du gilet',
     'À chaque fin d''exercice : bras levé dans les derniers mètres, tour complet sur soi, puis gonflage du gilet et signe OK.',
     'Ordre respecté sans rappel.'),
    (10, '9.4', 4, 'PERFECTIONNEMENT', 'Remontée sans repère',
     'Pleine eau, vitesse contrôlée sur l''ordinateur ou les plus petites bulles.',
     'Vitesse correcte sans repère visuel.'),
    (10, '9.5', 5, 'PERFECTIONNEMENT', 'Palier en pleine eau',
     'Palier simulé à 3 m, sans bout, profondeur lue régulièrement sur l''instrument. Lien avec la table fédérale et l''ordinateur.',
     '± 1 m pendant toute la durée annoncée.'),
    (10, '9.6', 6, 'PERFECTIONNEMENT', 'REC depuis 2 m puis 4 m',
     'Moniteur face à l''élève, mains sur ses sangles. Inspiration normale au fond, départ en palmant, embout en bouche, expiration continue et modérée jusqu''à la surface.',
     'Expiration ininterrompue, sans précipitation.'),
    (10, '9.7', 7, 'MAITRISE', 'REC depuis 6 m',
     'Départ du fond, 6 m maximum, inspiration normale, expiration continue, tour d''horizon à l''arrivée. Aucun critère de temps.',
     'Sans stress, vitesse correcte.'),
    (10, '9.8', 8, 'MAITRISE', 'Remontée complète en palanquée',
     'Signe du GP, remontée groupée, palier simulé, tour d''horizon, gilet gonflé, OK au bateau.',
     'Cohésion de la palanquée et sécurité en surface.'),
    (10, '9.9', 9, 'MAITRISE', 'Perte de palanquée',
     'Procédure briefée avant. Le moniteur se cache derrière un obstacle ; l''élève cherche brièvement, remonte seul à vitesse contrôlée et se signale en surface.',
     'Procédure appliquée calmement, sans recherche en profondeur.'),

    -- ---------- Competence « 10 » du document : Evoluer en securite (bloc 9 du MFT) ----------
    (9, '10.1', 1, 'INITIATION', 'Procédures au sec',
     'Au bord : signes panne d''air, essoufflement, ça ne va pas, froid, réserve ; emplacement de l''octopus du GP ; tenue par le gilet ; règle en cas de perte de palanquée.',
     'L''élève sait où est l''octopus et ce que fera le GP.'),
    (9, '10.2', 2, 'INITIATION', 'Panne d''air en statique',
     'À genoux à 3 m. Signe « panne d''air », prise de l''octopus présenté par le moniteur, tenue de son gilet, ventilation calme.',
     'Prise sans précipitation, ventilation calme ensuite.'),
    (9, '10.3', 3, 'INITIATION', 'Essoufflement, crampe, malaise',
     'À 3 m, incident annoncé. Essoufflement : arrêt et expiration longue tenu par le GP. Crampe : étirement en tirant la pointe de la palme. Malaise : « ça ne va pas », montrer où.',
     'Bon signe, aucune opposition à l''action du GP.'),
    (9, '10.4', 4, 'PERFECTIONNEMENT', 'Panne d''air : rejoindre le GP',
     'Apnée expiratoire vers le GP sur 3 m, puis 6 m, puis 10 m à l''horizontale ; prise de l''octopus et remontée tenue. Un second encadrant près de l''élève.',
     '10 m sans précipitation.'),
    (9, '10.5', 5, 'PERFECTIONNEMENT', 'Intervention en relais',
     'Deux élèves à 3 m. A signale une panne d''air ; B lui donne son octopus, le tient par le gilet et alerte le GP. Variante : simulation d''échange d''embout.',
     'Réaction immédiate, relais passé au GP.'),
    (9, '10.6', 6, 'PERFECTIONNEMENT', 'Mi-pression, réserve, froid',
     'Parcours à 3-5 m avec cartes-consignes de pression. L''élève signale, le GP organise le retour, la palanquée remonte groupée.',
     'Annonce spontanée, palanquée regroupée.'),
    (9, '10.7', 7, 'MAITRISE', 'Panne d''air sur 10 m',
     'Apnée expiratoire de 10 m à l''horizontale vers le GP, utilisation de son octopus, remontée tenue.',
     'Procédure automatique et sans erreur.'),
    (9, '10.8', 8, 'MAITRISE', 'Incidents tirés au sort',
     'Plusieurs incidents dans la même séance, en statique et en déplacement : essoufflement, crampe, malaise, froid, réserve.',
     'Bonne réaction à chaque incident, calme gardé.'),
    (9, '10.9', 9, 'MAITRISE', 'Scénario de palanquée',
     'Un équipier signale une difficulté pendant l''évolution : l''élève apporte une source d''air ou de l''aide et sollicite le GP.',
     'Action immédiate et adaptée.')
  ) AS v(bloc_ordre, numero, ordre, phase, intitule, deroulement, critere_reussite)
    ON v.bloc_ordre = b.ordre
 WHERE r.niveau = 'N1' AND r.version_mft = 'PE20 (2025-12)';
