-- ============================================================
--  Audit natif de Hibernate (Envers) : historise les entites
--  modifiables ou supprimables par un ADMIN. Les tables en ajout
--  seul (evaluation, journal des refresh tokens...) n'en ont pas
--  besoin, elles portent deja leur propre historique.
--
--  Schema genere une fois par Hibernate (ddl-auto=create sur une base
--  jetable) puis repris ici a la main, avec les memes conventions de
--  types que le reste du schema (VARCHAR bornes, TEXT pour le texte
--  libre) plutot que les types bruts choisis par H2.
-- ============================================================

CREATE TABLE revision_audit (
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    horodatage BIGINT      NOT NULL,
    -- Toujours issu du SecurityContext au moment de l'ecriture (EcouteurRevisionAudit).
    acteur     VARCHAR(180)
);

CREATE TABLE utilisateur_aud (
    rev             INTEGER NOT NULL REFERENCES revision_audit(id),
    revtype         SMALLINT,
    id              BIGINT  NOT NULL,
    email           VARCHAR(180),
    mot_de_passe    VARCHAR(100),
    nom             VARCHAR(80),
    prenom          VARCHAR(80),
    actif           BOOLEAN,
    niveau_encadrement VARCHAR(2),
    numero_licence  VARCHAR(30),
    cree_le         TIMESTAMP,
    PRIMARY KEY (rev, id)
);

CREATE TABLE eleve_aud (
    rev                        INTEGER NOT NULL REFERENCES revision_audit(id),
    revtype                    SMALLINT,
    id                         BIGINT  NOT NULL,
    nom                        VARCHAR(80),
    prenom                     VARCHAR(80),
    date_naissance             DATE,
    numero_licence             VARCHAR(30),
    certificat_valide_jusqu_au DATE,
    autorisation_legale        BOOLEAN,
    autorisation_image         BOOLEAN,
    utilisateur_id             BIGINT,
    archive_le                 TIMESTAMP,
    PRIMARY KEY (rev, id)
);

CREATE TABLE seance_aud (
    rev            INTEGER NOT NULL REFERENCES revision_audit(id),
    revtype        SMALLINT,
    id             BIGINT  NOT NULL,
    saison_id      BIGINT,
    date_seance    DATE,
    milieu         VARCHAR(12),
    lieu           VARCHAR(120),
    profondeur_max INT,
    dp_id          BIGINT,
    commentaire    TEXT,
    PRIMARY KEY (rev, id)
);

CREATE TABLE cursus_aud (
    rev                  INTEGER NOT NULL REFERENCES revision_audit(id),
    revtype              SMALLINT,
    id                   BIGINT  NOT NULL,
    eleve_id             BIGINT,
    saison_id            BIGINT,
    referentiel_id       BIGINT,
    moniteur_referent_id BIGINT,
    statut               VARCHAR(20),
    ouvert_le            DATE,
    PRIMARY KEY (rev, id)
);

CREATE TABLE validation_competence_aud (
    rev             INTEGER NOT NULL REFERENCES revision_audit(id),
    revtype         SMALLINT,
    id              BIGINT  NOT NULL,
    cursus_id       BIGINT,
    bloc_id         BIGINT,
    moniteur_id     BIGINT,
    date_validation DATE,
    commentaire     TEXT,
    PRIMARY KEY (rev, id)
);

CREATE TABLE delivrance_aud (
    rev                              INTEGER NOT NULL REFERENCES revision_audit(id),
    revtype                          SMALLINT,
    id                               BIGINT  NOT NULL,
    cursus_id                        BIGINT,
    delivre_par_id                   BIGINT,
    date_delivrance                  DATE,
    numero_brevet                    VARCHAR(40),
    plongees_milieu_naturel_a_faire  INT,
    echeance_plongees                DATE,
    PRIMARY KEY (rev, id)
);
