-- ============================================================
--  Appartenance d'un élève à une saison, indépendamment de toute formation.
--
--  Jusqu'ici le seul lien élève-saison passait par un Cursus (N1/N2/N3) :
--  un élève déjà breveté qui continue de plonger avec le club sans viser un
--  nouveau niveau ne pouvait apparaître dans aucune saison. La table
--  `adhesion_saison` comble ce trou : une ligne = un élève fait partie du
--  club pour cette saison, sans référentiel ni suivi de séances (voir
--  CLAUDE.md - décision volontaire, à ne pas confondre avec Cursus).
--
--  Pas d'audit Envers : au même titre que `participation`, une adhésion est
--  une donnée d'appartenance légère, pas une entité métier suivie dans le
--  temps comme Eleve ou Cursus.
-- ============================================================

CREATE TABLE adhesion_saison (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    eleve_id    BIGINT NOT NULL REFERENCES eleve(id) ON DELETE CASCADE,
    saison_id   BIGINT NOT NULL REFERENCES saison(id) ON DELETE CASCADE,
    adhere_le   DATE   NOT NULL DEFAULT CURRENT_DATE,
    CONSTRAINT uq_adhesion_saison UNIQUE (eleve_id, saison_id)
);
CREATE INDEX idx_adhesion_saison_saison ON adhesion_saison(saison_id);
